[package]
name = "xark-grumpkin"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
name = "xark_grumpkin"
path = "src/lib.rs"

[dependencies]
xark = { path = "../xark", default-features = false }

[dev-dependencies]
xark-test-harness = { path = "../xark-test-harness" }
xark-ir = { path = "../xark-ir" }
