[package]
name = "on_curve_ed25519"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", version = "0.2.2" }
xark-ed25519 = { path = "../../gadgets/xark-ed25519", version = "0.2.2" }

[dev-dependencies]
xark-ed25519 = { path = "../../gadgets/xark-ed25519", version = "0.2.2" }

[workspace]
