[package]
name = "xark-keccak"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
name = "xark_keccak"
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", default-features = false }
xark-bits = { path = "../xark-bits" }
xark-hash = { path = "../xark-hash" }
