// xark-client — an IDL-driven client for xark zero-knowledge circuits.
//
// The TypeScript analog of Anchor's `Program`: one hand-written library, and the
// per-circuit part is just the IDL you pass in. Verify proofs off-chain with
// snarkjs, and get the exact bytes to submit on-chain.
//
//   import { XarkClient } from "xark-client";
//   import { cubeIdl } from "./cube.idl";      // generated by `xark client`
//
//   const client = new XarkClient(cubeIdl);
//   await client.verify(bundle);          // snarkjs verify (embedded VK)
//   const data = client.calldata(bundle); // packed proof ‖ public bytes
//
// Proving happens in the `xark` CLI (`xark prove …`): snarkjs can verify an
// xark proof but cannot generate one, so there is no `prove` here by design.

import * as snarkjs from "snarkjs";

/** A declared circuit input. */
export interface IdlInput {
  name: string;
  visibility: "public" | "private";
}

/** The verifying key embedded in the IDL (present once `xark setup` has run). */
export interface IdlVerifyingKey {
  production_safe: boolean;
  /** snarkjs `verification_key.json` shape — fed straight to `groth16.verify`. */
  snarkjs: unknown;
  /** The on-chain Solana VK blob (little-endian), hex-encoded. */
  solana_le_hex: string;
}

/** The packed `proof ‖ public_inputs` calldata layout a verifier consumes. */
export interface IdlCalldata {
  endianness: "little";
  proof_bytes: number;
  public_input_bytes: number;
  total_bytes: number;
  layout: string;
}

/** A circuit IDL (`<name>.idl.json` / `<name>.idl.ts`) — its full ABI. */
export interface Idl {
  xark_idl_version: string;
  name: string;
  circuit_hash: string;
  field: string;
  curve: string;
  protocol: string;
  inputs: readonly IdlInput[];
  /** Public inputs in the exact order the proof commits to them. */
  public_signals: readonly string[];
  num_public_inputs: number;
  num_private_inputs: number;
  num_constraints: number;
  calldata: IdlCalldata;
  verifying_key?: IdlVerifyingKey;
}

/** A snarkjs Groth16 proof. */
export interface SnarkjsProof {
  pi_a: string[];
  pi_b: string[][];
  pi_c: string[];
  protocol: string;
  curve: string;
}

/** A proof bundle as written by `xark prove` (`<name>-<hash>.proof.json`). */
export interface ProofBundle {
  circuit: string;
  circuit_hash: string;
  proof_sha256: string;
  public_signals: string[];
  proof: SnarkjsProof;
  calldata: {
    endianness: string;
    hex: string;
    proof_hex: string;
    public_inputs_hex: string;
  };
}

/**
 * The public signals of a circuit as a typed `{ name: value }` object, inferred
 * from an `as const` IDL. For `cubeIdl` (public_signals `["result"]`) this is
 * `{ result: string }`. This is the "typed from the IDL" payoff, like Anchor's
 * `Program<Idl>`.
 */
export type PublicSignals<I extends Idl> = {
  [K in I["public_signals"][number]]: string;
};

/**
 * The circuit's inputs as a typed object, inferred from the IDL's input names.
 * For `cubeIdl` this is `{ secret: …; result: … }`. Values are field elements,
 * given as decimal strings, numbers, or bigints. Use this to type the inputs
 * you pass to a prover (the `xark` CLI, or a Node wrapper around it).
 */
export type Inputs<I extends Idl> = {
  [K in I["inputs"][number]["name"]]: string | number | bigint;
};

/** Decode a `0x…`/bare hex string into bytes (browser- and Node-safe). */
export function hexToBytes(hex: string): Uint8Array {
  const h = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (h.length % 2 !== 0) throw new Error("odd-length hex string");
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

/**
 * A circuit client, constructed from its IDL. Generic over the IDL type so a
 * typed IDL (`import { cubeIdl } from "./cube.idl"`) flows through to typed
 * public signals.
 */
export class XarkClient<I extends Idl = Idl> {
  constructor(readonly idl: I) {
    if (!idl.verifying_key) {
      throw new Error(
        `IDL for '${idl.name}' has no verifying key — run \`xark setup\` and regenerate the IDL.`,
      );
    }
  }

  /** The circuit name. */
  get name(): string {
    return this.idl.name;
  }

  /** Public-signal names, in the order the proof commits to them (typed). */
  get publicSignalOrder(): I["public_signals"] {
    return this.idl.public_signals;
  }

  /** Verify a proof bundle (as written by `xark prove`) with snarkjs. */
  verify(bundle: ProofBundle): Promise<boolean> {
    return this.verifyRaw(bundle.proof, bundle.public_signals);
  }

  /** Verify a raw snarkjs proof against ordered public signals. */
  verifyRaw(proof: SnarkjsProof, publicSignals: string[]): Promise<boolean> {
    return snarkjs.groth16.verify(this.idl.verifying_key!.snarkjs, publicSignals, proof);
  }

  /** A bundle's ordered public signals as a typed `{ name: value }` object. */
  publicSignals(bundle: ProofBundle): PublicSignals<I> {
    const out: Record<string, string> = {};
    this.idl.public_signals.forEach((name, i) => {
      out[name] = bundle.public_signals[i];
    });
    return out as PublicSignals<I>;
  }

  /**
   * The packed verifier calldata: `proof (256 B) || public_inputs (N * 32 B)`,
   * little-endian — what a verifier built with `xark export` consumes. Your
   * program owns the accounts and any instruction discriminator; drop these
   * bytes where your verifier expects the proof.
   */
  calldata(bundle: ProofBundle): Uint8Array {
    return hexToBytes(bundle.calldata.hex);
  }
}
