//! An ergonomic 256-bit SHA-256 digest wrapper.
//!
//! Consuming a hash in a circuit means "compute `sha256(bytes)`, then constrain
//! the digest equals a known value". The raw [`xark_sha256::sha256`] output is
//! `[[Field; 32]; 8]` — 8 words × 32 little-endian bits — and comparing it to a
//! literal `[u8; 32]` hash requires reproducing SHA-256's word/byte/bit layout
//! by hand (big-endian bytes within each word, LSB-first bits within each byte).
//! [`Digest`] hides that bookkeeping so a circuit reads:
//!
//! ```rust,ignore
//! use xark_sha256::prelude::*; // re-exports `Digest`
//!
//! const EXPECTED: [u8; 32] = [/* known hash */];
//!
//! #[circuit]
//! pub fn circuit(msg: Private<[u8; N]>) {
//!     let expected: Digest = EXPECTED.into();
//!     Digest::from(sha256(msg)).require_eq(expected);
//! }
//! ```
//!
//! Unlike [`Hash`](crate::Hash), a `Digest` keeps all 256 bits, so a
//! `Public<Digest>` is 256 public inputs — use it for a **constant** expected
//! hash baked into the circuit (no public inputs), and use [`Hash`](crate::Hash)
//! for a runtime public digest.
//!
//! ## Layout (must match [`xark_sha256::sha256`])
//!
//! The gadget returns the 256-bit hash as 8 words. Word `w` covers digest bytes
//! `4w .. 4w+4` **big-endian**: byte position `k` within the word (`k = 0` is the
//! most-significant) occupies word bits `(3-k)*8 .. (3-k)*8+8`. Within a byte the
//! 8 bits are **LSB-first** (matching [`Field::to_bits`]). So the digest byte at
//! standard hex index `idx` (`idx = 0` is the leading hex pair) lands in word
//! `idx / 4`, byte slot `idx % 4`, and its bit `j` (`(b >> j) & 1`) at word bit
//! `(3 - idx%4)*8 + j`. This module's [`From<[u8; 32]>`] places the known bytes
//! at exactly those positions; the KAT test `sha256("abc")` confirms it.

use xark::{require_eq, CircuitInput, Field, RequireEqCircuit};

/// A 256-bit SHA-256 digest, stored in [`xark_sha256::sha256`]'s native output
/// layout: 8 words × 32 little-endian bits (`[[Field; 32]; 8]`).
///
/// Build one from the gadget output (`Digest::from(sha256(msg))`) or from a known
/// hash constant (`EXPECTED.into()` for `const EXPECTED: [u8; 32]`), then pin the
/// two together with [`Digest::require_eq`].
///
/// `#[derive(CircuitInput)]` generates `Into<[Field; 256]>` in the compiler's
/// structural-flatten order (word-major, then bit — `bits[w][j]` → index
/// `w*32 + j`), so `Digest` works as a `Public<Digest>`/`Private<Digest>` input
/// *and* a host-side input builder can drive it from a native hash with the
/// leaf order guaranteed (not merely disciplined) to match the circuit's.
#[derive(Clone, Copy, CircuitInput)]
pub struct Digest {
    /// 8 words × 32 little-endian bits, identical to the `sha256` gadget output.
    bits: [[Field; 32]; 8],
}

impl Digest {
    /// Constrain this digest equal to `other`, bit-for-bit (256 equality
    /// constraints, one per output bit). Both digests are already in the same
    /// word/byte/bit layout, so this is a plain element-wise compare.
    pub fn require_eq(self, other: Digest) {
        let mut w = 0usize;
        while w < 8usize {
            let mut j = 0usize;
            while j < 32usize {
                require_eq(self.bits[w][j], other.bits[w][j]);
                j += 1;
            }
            w += 1;
        }
    }
}

/// Wrap the raw [`xark_sha256::sha256`] output directly — it is already in this
/// type's storage layout, so this is a zero-constraint move.
impl From<[[Field; 32]; 8]> for Digest {
    fn from(bits: [[Field; 32]; 8]) -> Digest {
        Digest { bits }
    }
}

/// Let a `#[circuit]` body write `require_eq(sha256(msg), expected)` directly: the
/// raw gadget output `[[Field; 32]; 8]` is wrapped and compared bit-for-bit
/// against the expected [`Digest`]. See [`RequireEqCircuit`] for the dispatch.
impl RequireEqCircuit<Digest> for [[Field; 32]; 8] {
    #[inline]
    fn require_eq_circuit(self, rhs: Digest) {
        Digest::from(self).require_eq(rhs);
    }
}

/// Compare two digests (e.g. `require_eq(a, b)` where both are already `Digest`).
impl RequireEqCircuit<Digest> for Digest {
    #[inline]
    fn require_eq_circuit(self, rhs: Digest) {
        self.require_eq(rhs);
    }
}

// `Into<[Field; 256]>` (i.e. `From<Digest> for [Field; 256]`) is generated by
// `#[derive(CircuitInput)]` above, in the compiler's structural-flatten order.
// Pin the arity at compile time — a wrong `Into` length would fail to resolve:
const _: fn(Digest) -> [Field; 256] = <Digest as core::convert::Into<[Field; 256]>>::into;

/// Build a **constant** digest from a known 32-byte hash (e.g. a test vector or a
/// value baked into the circuit). Each of the 32 bytes is placed into the same
/// word/byte/bit slot the `sha256` gadget uses, as `Field` `0`/`1` constants — no
/// witnesses and no constraints. See the module docs for the layout.
impl From<[u8; 32]> for Digest {
    fn from(bytes: [u8; 32]) -> Digest {
        let zero = [Field::from(0u8); 32];
        let mut bits = [zero; 8];
        let mut idx = 0usize;
        while idx < 32usize {
            let b = bytes[idx];
            // Digest byte `idx` → word `idx/4`, big-endian slot `idx%4` (slot 0 is
            // the most-significant), which occupies word bits `(3 - idx%4)*8 ..`.
            let w = idx / 4usize;
            let off = (3usize - (idx % 4usize)) * 8usize;
            // The 8 byte bits are LSB-first (matching `Field::to_bits::<8>`).
            let mut j = 0usize;
            while j < 8usize {
                bits[w][off + j] = Field::from((b >> j) & 1u8);
                j += 1;
            }
            idx += 1;
        }
        Digest { bits }
    }
}
