[package]
name = "keccak256"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", version = "0.2.1", default-features = false }
xark-keccak = { path = "../../gadgets/xark-keccak", version = "0.2.1" }

[dev-dependencies]
sha3 = "0.10"

[target.'cfg(not(xark))'.dependencies]
xark-prover = { path = "../../crates/prover", version = "0.2.1" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(xark)'] }

[workspace]
