[package]
name = "ed25519"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/xark", default-features = false }
xark-bignum = { path = "../../crates/xark-bignum" }
xark-ed25519 = { path = "../../crates/xark-ed25519" }
xark-prover = { path = "../../crates/xark-prover", optional = true }

[dev-dependencies]
xark-ed25519 = { path = "../../crates/xark-ed25519", features = ["host"] }
xark-prover = { path = "../../crates/xark-prover" }
ed25519-dalek = "2"

[features]
host = ["dep:xark-prover", "xark-ed25519/host"]

[workspace]
