[package]
name = "xark-mimc"
description = "MiMC hash gadget for xark zero-knowledge circuits."
keywords = ["zero-knowledge", "zk", "cryptography", "circuit", "groth16"]
categories = ["cryptography"]
readme = "README.md"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true

[lib]
name = "xark_mimc"
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", version = "0.0.1", default-features = false }

[dev-dependencies]
xark-test-harness = { path = "../../crates/test-harness", version = "0.0.1" }
xark-ir = { path = "../../crates/ir", version = "0.0.1" }
