[package]
name = "poseidon2_sponge"
version = "0.0.0"
edition = "2024"
publish = false
[lib]
[dependencies]
xark = { path = "../../crates/lang", version = "0.2.0", default-features = false }
xark-poseidon2 = { path = "../../gadgets/xark-poseidon2", version = "0.2.0" }

[target.'cfg(not(xark))'.dependencies]
xark-prover = { path = "../../crates/prover", version = "0.2.0" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(xark)'] }
