//! EVM Solidity verifier exporter.
//!
//! Emits a self-contained `Verifier.sol` that hardcodes a Groth16 BN254
//! verifying key and exposes:
//!
//! ```solidity
//! function verifyProof(
//!     uint256[2] memory a,
//!     uint256[2][2] memory b,
//!     uint256[2] memory c,
//!     uint256[N] memory inputs
//! ) public view returns (bool);
//! ```
//!
//! The check is the standard Groth16 pairing equation evaluated through the
//! Ethereum BN254 precompiles (`0x06` G1 add, `0x07` G1 mul, `0x08` pairing):
//!
//! ```text
//! e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) = 1
//! ```
//! with `vk_x = ic[0] + sum_i inputs[i] * ic[i+1]`.
//!
//! ## Endianness / coordinate ordering
//!
//! * G1 = `(x, y)` over Fq. Both fields emitted as big-endian 32-byte words.
//! * G2 = `(c0 + c1*u)`. Internally arkworks stores `Fq2 { c0, c1 }`. The
//!   Ethereum precompile expects each Fq2 coordinate as `(c1, c0)` (i.e.
//!   the imaginary part first, then the real part). This is the same
//!   convention used by snarkjs's Solidity template and by every audited
//!   Tornado-style verifier we have looked at. See the test in
//!   `crates/groth16-backend/tests/evm_export.rs` plus the unit test below.

use std::fmt::Write as _;

use ark_bn254::{Bn254, Fq, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_groth16::VerifyingKey;
use num_bigint::BigUint;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum EvmExportError {
    /// The verifying key has no IC entries. The first entry is required even
    /// for circuits with zero public inputs.
    #[error("verifying key has empty gamma_abc_g1 (need at least 1 element)")]
    EmptyIc,
}

/// Generate a single-file Solidity Groth16 verifier from `vk`.
///
/// The number of public inputs is inferred from `vk.gamma_abc_g1.len() - 1`.
pub fn export_verifier_solidity(vk: &VerifyingKey<Bn254>) -> Result<String, EvmExportError> {
    if vk.gamma_abc_g1.is_empty() {
        return Err(EvmExportError::EmptyIc);
    }
    let num_inputs = vk.gamma_abc_g1.len() - 1;
    Ok(render(vk, num_inputs))
}

fn render(vk: &VerifyingKey<Bn254>, num_inputs: usize) -> String {
    let alpha = g1_struct(&vk.alpha_g1);
    let beta = g2_struct(&vk.beta_g2);
    let gamma = g2_struct(&vk.gamma_g2);
    let delta = g2_struct(&vk.delta_g2);

    // IC array literal entries, one per element.
    let mut ic_lines = String::new();
    for (i, point) in vk.gamma_abc_g1.iter().enumerate() {
        let (x, y) = xy_of_g1(point);
        let _ = writeln!(
            ic_lines,
            "        vk.ic[{}] = Pairing.G1Point({}, {});",
            i,
            fq_hex(&x),
            fq_hex(&y),
        );
    }

    // The inner input-arity literal used both in the function signature and
    // in the IC array length.
    let ic_len = vk.gamma_abc_g1.len();

    format!(
        "// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// Auto-generated by xark `export evm`.
// Groth16 BN254 verifier for a circuit with {num_inputs} public input(s).
// DO NOT EDIT — regenerate with `xark export evm`.

library Pairing {{
    struct G1Point {{
        uint256 X;
        uint256 Y;
    }}
    // Encoding of a field element of Fq2 as (c1, c0) — imaginary part first.
    struct G2Point {{
        uint256[2] X;
        uint256[2] Y;
    }}

    /// The BN254 base field prime `p`.
    uint256 internal constant Q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// Return the additive inverse of `p` on G1: `(x, p - y)`.
    function negate(G1Point memory p) internal pure returns (G1Point memory) {{
        if (p.X == 0 && p.Y == 0) {{
            return G1Point(0, 0);
        }}
        return G1Point(p.X, Q - (p.Y % Q));
    }}

    /// G1 addition via the `0x06` precompile.
    function addition(G1Point memory p1, G1Point memory p2)
        internal
        view
        returns (G1Point memory r)
    {{
        uint256[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;
        bool success;
        assembly {{
            success := staticcall(sub(gas(), 2000), 6, input, 0x80, r, 0x40)
        }}
        require(success, \"pairing-add-failed\");
    }}

    /// G1 scalar multiplication via the `0x07` precompile.
    function scalar_mul(G1Point memory p, uint256 s)
        internal
        view
        returns (G1Point memory r)
    {{
        uint256[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;
        bool success;
        assembly {{
            success := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x40)
        }}
        require(success, \"pairing-mul-failed\");
    }}

    /// Pairing check via the `0x08` precompile.
    /// Returns true iff prod_i e(p1[i], p2[i]) == 1 in GT.
    function pairing(G1Point[] memory p1, G2Point[] memory p2)
        internal
        view
        returns (bool)
    {{
        require(p1.length == p2.length, \"pairing-length-mismatch\");
        uint256 elements = p1.length;
        uint256 inputSize = elements * 6;
        uint256[] memory input = new uint256[](inputSize);
        for (uint256 i = 0; i < elements; i++) {{
            input[i * 6 + 0] = p1[i].X;
            input[i * 6 + 1] = p1[i].Y;
            input[i * 6 + 2] = p2[i].X[0];
            input[i * 6 + 3] = p2[i].X[1];
            input[i * 6 + 4] = p2[i].Y[0];
            input[i * 6 + 5] = p2[i].Y[1];
        }}
        uint256[1] memory out;
        bool success;
        assembly {{
            success := staticcall(
                sub(gas(), 2000),
                8,
                add(input, 0x20),
                mul(inputSize, 0x20),
                out,
                0x20
            )
        }}
        require(success, \"pairing-opcode-failed\");
        return out[0] != 0;
    }}
}}

contract Verifier {{
    using Pairing for *;

    /// BN254 scalar field order `r`.
    uint256 internal constant R =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    struct VerifyingKey {{
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[{ic_len}] ic;
    }}

    struct Proof {{
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }}

    function verifyingKey() internal pure returns (VerifyingKey memory vk) {{
        vk.alpha = {alpha};
        vk.beta = {beta};
        vk.gamma = {gamma};
        vk.delta = {delta};
{ic_lines}    }}

    /// Verify a Groth16 proof for this circuit.
    ///
    /// Reverts on invalid precompile calls. Returns `true` iff the proof
    /// is accepted by the pairing check.
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[{num_inputs}] memory inputs
    ) public view returns (bool) {{
        VerifyingKey memory vk = verifyingKey();

        // Range check public inputs against the BN254 scalar field order.
        for (uint256 i = 0; i < inputs.length; i++) {{
            require(inputs[i] < R, \"verifier-input-gte-r\");
        }}

        // Compute the linear combination vk_x.
        Pairing.G1Point memory vk_x = vk.ic[0];
        for (uint256 i = 0; i < inputs.length; i++) {{
            vk_x = Pairing.addition(
                vk_x,
                Pairing.scalar_mul(vk.ic[i + 1], inputs[i])
            );
        }}

        // Repack the user inputs into Pairing structs.
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        // Solidity passes b as [[bx0, bx1], [by0, by1]] following the same
        // (c1, c0) imaginary-part-first convention used by the precompile.
        proof.B = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.C = Pairing.G1Point(c[0], c[1]);

        // Build the pairing inputs:
        //   e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1.
        Pairing.G1Point[] memory p1 = new Pairing.G1Point[](4);
        Pairing.G2Point[] memory p2 = new Pairing.G2Point[](4);
        p1[0] = Pairing.negate(proof.A);
        p2[0] = proof.B;
        p1[1] = vk.alpha;
        p2[1] = vk.beta;
        p1[2] = vk_x;
        p2[2] = vk.gamma;
        p1[3] = proof.C;
        p2[3] = vk.delta;
        return Pairing.pairing(p1, p2);
    }}
}}
"
    )
}

// -- helpers ------------------------------------------------------------------

/// Format an Fq element as `0x` + 64 hex chars (uint256 BE).
fn fq_hex(value: &Fq) -> String {
    let big: BigUint = (*value).into();
    let bytes = big.to_bytes_be();
    let mut out = String::with_capacity(2 + 64);
    out.push_str("0x");
    for _ in bytes.len()..32 {
        out.push_str("00");
    }
    for b in bytes {
        let _ = write!(out, "{:02x}", b);
    }
    out
}

/// Extract `(x, y)` from a G1 point, returning zero coordinates for the
/// identity element.
fn xy_of_g1(p: &G1Affine) -> (Fq, Fq) {
    if p.is_zero() {
        (Fq::from(0u64), Fq::from(0u64))
    } else {
        let (x, y) = p.xy().expect("g1 not at infinity");
        (x, y)
    }
}

/// `Pairing.G1Point(0x..x, 0x..y)` constructor literal.
fn g1_struct(p: &G1Affine) -> String {
    let (x, y) = xy_of_g1(p);
    format!("Pairing.G1Point({}, {})", fq_hex(&x), fq_hex(&y))
}

/// `Pairing.G2Point([c1, c0], [c1, c0])` constructor literal.
///
/// Arkworks stores Fq2 internally as `{ c0, c1 }`. The Ethereum BN254
/// pairing precompile expects each Fq2 coordinate in `(c1, c0)` order,
/// i.e. imaginary part first then real part. See `serialization::g2_to_json`
/// for the JSON-side ordering convention (which is the arkworks-native
/// `[c0, c1]` order).
fn g2_struct(p: &G2Affine) -> String {
    use ark_bn254::Fq2;
    let (x, y) = if p.is_zero() {
        (Fq2::default(), Fq2::default())
    } else {
        p.xy().expect("g2 not at infinity")
    };
    format!(
        "Pairing.G2Point([{}, {}], [{}, {}])",
        fq_hex(&x.c1),
        fq_hex(&x.c0),
        fq_hex(&y.c1),
        fq_hex(&y.c0),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_bn254::Fr;
    use ark_ec::{AffineRepr, CurveGroup};
    use ark_ff::UniformRand;
    use ark_std::test_rng;

    #[test]
    fn fq_hex_pads_to_32_bytes() {
        let one = Fq::from(1u64);
        let s = fq_hex(&one);
        assert_eq!(s.len(), 2 + 64);
        assert!(s.starts_with("0x"));
        assert!(s.ends_with('1'));
        // Leading zeros preserved.
        assert_eq!(
            &s[..18],
            "0x0000000000000000",
            "leading hex bytes must be zero-padded"
        );
    }

    #[test]
    fn g2_struct_uses_c1_c0_ordering() {
        // Build a deterministic G2 point and check that the formatted struct
        // mentions c1 before c0 for both X and Y.
        let mut rng = test_rng();
        let p = ark_bn254::G2Projective::rand(&mut rng).into_affine();
        let (x, y) = p.xy().unwrap();
        let s = g2_struct(&p);
        let pos_x_c1 = s.find(&fq_hex(&x.c1)).expect("x.c1 present");
        let pos_x_c0 = s.find(&fq_hex(&x.c0)).expect("x.c0 present");
        let pos_y_c1 = s.find(&fq_hex(&y.c1)).expect("y.c1 present");
        let pos_y_c0 = s.find(&fq_hex(&y.c0)).expect("y.c0 present");
        assert!(
            pos_x_c1 < pos_x_c0,
            "G2 X coordinate must serialize as (c1, c0): {s}"
        );
        assert!(
            pos_y_c1 < pos_y_c0,
            "G2 Y coordinate must serialize as (c1, c0): {s}"
        );
    }

    #[test]
    fn export_minimal_vk_shape() {
        // Synthesize a fake VK with one IC element (zero public inputs).
        // We don't care about cryptographic validity here, only string shape.
        let g1 = G1Affine::generator();
        let g2 = G2Affine::generator();
        let vk = VerifyingKey::<Bn254> {
            alpha_g1: g1,
            beta_g2: g2,
            gamma_g2: g2,
            delta_g2: g2,
            gamma_abc_g1: vec![g1],
        };
        let s = export_verifier_solidity(&vk).expect("export");
        assert!(s.contains("pragma solidity ^0.8.0;"));
        assert!(s.contains("contract Verifier"));
        assert!(s.contains("uint256[0] memory inputs"));
        // Cheap sanity check that an `Fr` modulus appears.
        let _ = Fr::from(1u64);
    }
}
