[package]
name = "grumpkin"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", version = "0.2.2" }
xark-grumpkin = { path = "../../gadgets/xark-grumpkin", version = "0.2.2" }

[dev-dependencies]
xark-grumpkin = { path = "../../gadgets/xark-grumpkin", version = "0.2.2" }

[workspace]
