[package]
name = "ec_incomplete_r1"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", version = "0.2.2" }
xark-secp256r1 = { path = "../../gadgets/xark-secp256r1", version = "0.2.2" }

[dev-dependencies]
xark-secp256r1 = { path = "../../gadgets/xark-secp256r1", version = "0.2.2" }
p256 = "0.13"

[workspace]
