[package]
name = "keccak256_test"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/xark", default-features = false }
xark-keccak = { path = "../../crates/xark-keccak" }

xark-prover = { path = "../../crates/xark-prover", optional = true }

[dev-dependencies]
xark-prover = { path = "../../crates/xark-prover" }
sha3 = "0.10"

[features]
host = ["dep:xark-prover"]
