[package]
name = "poseidon_sponge"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
[dependencies]
xark = { path = "../../crates/xark", default-features = false }
xark-poseidon = { path = "../../crates/xark-poseidon" }

[target.'cfg(not(xark))'.dependencies]
xark-prover = { path = "../../crates/xark-prover" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(xark)'] }
