[package]
name = "xark-grumpkin"
description = "Grumpkin curve gadget for xark zero-knowledge circuits."
keywords = ["zero-knowledge", "zk", "cryptography", "circuit", "groth16"]
categories = ["cryptography"]
readme = "README.md"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true

[lib]
name = "xark_grumpkin"
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", version = "0.2.2" }

[dev-dependencies]
xark-test-harness = { path = "../../crates/test-harness", version = "0.2.2" }
xark-ir = { path = "../../crates/ir", version = "0.2.2" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(xark)'] }
