//! The host API generated by `#[circuit]` uses `Field` for scalar and array
//! field inputs. Decimal strings exist only at the prover/CLI serialization edge.

use xark::prelude::*;

const SIBLINGS: usize = 2;

#[circuit]
pub fn field_values(value: Private<Field>, siblings: Public<[Field; SIBLINGS]>) {
    require_eq(value, siblings[0]);
}

#[test]
fn generated_inputs_keep_field_types() {
    let _validator: fn(Field, [Field; SIBLINGS]) -> Result<(), xark::__private::ProveError> =
        field_values;
    let inputs = FieldValuesInputs {
        value: Field::from(7u64),
        siblings: [Field::from(7u64), Field::from(9u64)],
    };
    let leaves = xark::__private::ProveInputs::into_inputs(inputs);
    assert_eq!(
        leaves,
        vec![
            ("value".to_string(), "7".to_string()),
            ("siblings[0]".to_string(), "7".to_string()),
            ("siblings[1]".to_string(), "9".to_string()),
        ]
    );
}
