[package]
name = "xark-merkle"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
name = "xark_merkle"
path = "src/lib.rs"

[dependencies]
xark = { path = "../xark", default-features = false }
xark-poseidon = { path = "../xark-poseidon" }

[dev-dependencies]
xark-test-harness = { path = "../xark-test-harness" }
xark-ir = { path = "../xark-ir" }
num-bigint = "0.4"

[lints]
workspace = true
