[package]
name = "mimc_test"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/xark", default-features = false }
xark-mimc = { path = "../../crates/xark-mimc" }

xark-prover = { path = "../../crates/xark-prover", optional = true }

[dev-dependencies]
xark-prover = { path = "../../crates/xark-prover" }

[features]
host = ["dep:xark-prover"]
