[package]
name = "blake2s"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", version = "0.2.2" }
xark-blake2s = { path = "../../gadgets/xark-blake2s", version = "0.2.2" }

[dev-dependencies]
blake2 = "0.10"

[workspace]
