[package]
name = "ed25519_smul"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/xark", default-features = false }
xark-ff = { path = "../../crates/xark-ff" }
xark-ed25519 = { path = "../../crates/xark-ed25519" }
