[package]
name = "bignum_ops"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
xark = { path = "../../crates/lang", default-features = false }
xark-bignum = { path = "../../gadgets/xark-bignum" }

[target.'cfg(not(xark))'.dependencies]
xark-prover = { path = "../../crates/prover" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(xark)'] }

[workspace]
