//! `#[circuit]` — mark a circuit entry function and generate a typed input
//! struct for its `xark_prover` tests.
//!
//! Given `pub fn cube(secret: Private<Field>, result: Public<Field>)`, it emits
//! a `CubeInputs { secret, result }` struct so tests read
//! `prove(CubeInputs { secret: 2, result: 4 })` instead of positional `[2, 4]`
//! — named, so parameters can't be transposed by accident.
//!
//! The struct and its `ProveInputs` impl are `#[cfg(test)]`-gated: `xark_prover`
//! is a dev-dependency, and proving from the circuit crate is a test-time
//! convenience. The entry function is emitted unchanged, so `xark build`
//! extracts it exactly as it would without the attribute.

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_macro_input, FnArg, ItemFn, Pat};

#[proc_macro_attribute]
pub fn circuit(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let func = parse_macro_input!(item as ItemFn);
    let struct_name = format_ident!("{}Inputs", to_pascal(&func.sig.ident.to_string()));

    // Parameter names, in declaration order — the struct fields.
    let fields: Vec<syn::Ident> = func
        .sig
        .inputs
        .iter()
        .filter_map(|arg| match arg {
            FnArg::Typed(pt) => match &*pt.pat {
                Pat::Ident(pi) => Some(pi.ident.clone()),
                _ => None,
            },
            FnArg::Receiver(_) => None,
        })
        .collect();
    let field_strs: Vec<String> = fields.iter().map(|f| f.to_string()).collect();

    quote! {
        #func

        /// Typed inputs for this circuit (generated by `#[circuit]`). Field
        /// elements are given as `i128`, reduced into the field.
        #[cfg(test)]
        #[derive(Clone, Copy, Debug)]
        pub struct #struct_name {
            #( pub #fields: i128, )*
        }

        #[cfg(test)]
        impl ::xark_prover::ProveInputs for #struct_name {
            fn into_inputs(self) -> ::std::vec::Vec<(&'static str, i128)> {
                ::std::vec![ #( (#field_strs, self.#fields), )* ]
            }
        }
    }
    .into()
}

/// `my_square` → `MySquare` (for the `<Name>Inputs` struct).
fn to_pascal(s: &str) -> String {
    s.split('_')
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
