//! `#[circuit]` — mark a circuit entry function and generate a typed input
//! struct for its `xark_prover` tests.
//!
//! Given `pub fn cube(secret: Private<Field>, result: Public<Field>)`, it emits
//! a `CubeInputs { secret, result }` struct so tests read
//! `check(CubeInputs { secret: 2, result: 4 }).unwrap()` instead of positional
//! `[2, 4]` — named, so parameters can't be transposed by accident.
//!
//! The struct and its `ProveInputs` impl are `#[cfg(test)]`-gated: `xark_prover`
//! is a dev-dependency, and proving from the circuit crate is a test-time
//! convenience. The entry function is emitted unchanged, so `xark build`
//! extracts it exactly as it would without the attribute.

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_macro_input, FnArg, ItemFn, Pat};

#[proc_macro_attribute]
pub fn circuit(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let func = parse_macro_input!(item as ItemFn);
    let struct_name = format_ident!("{}Inputs", to_pascal(&func.sig.ident.to_string()));

    // Struct fields = the entry's parameter names, in declaration order. A
    // circuit parameter must be a plain identifier (it has to be referenced in
    // the body anyway); reject anything else with a clear compile error rather
    // than silently dropping it — a dropped field would desync the struct from
    // the circuit's declared inputs and panic at prove time.
    let mut fields: Vec<syn::Ident> = Vec::new();
    for arg in &func.sig.inputs {
        match arg {
            FnArg::Typed(pt) => match &*pt.pat {
                Pat::Ident(pi) => fields.push(pi.ident.clone()),
                other => {
                    return syn::Error::new_spanned(
                        other,
                        "#[circuit] parameters must be plain identifiers (no `_`, no patterns)",
                    )
                    .to_compile_error()
                    .into();
                }
            },
            FnArg::Receiver(r) => {
                return syn::Error::new_spanned(r, "#[circuit] cannot take a `self` parameter")
                    .to_compile_error()
                    .into();
            }
        }
    }
    let field_strs: Vec<String> = fields.iter().map(|f| f.to_string()).collect();

    quote! {
        #func

        /// Typed inputs for this circuit (generated by `#[circuit]`). Values are
        /// `i128` (reduced into the field) — enough for ordinary test inputs. For
        /// inputs wider than 127 bits (hash digests, curve coordinates), prove
        /// from the CLI, which takes full decimals: `xark prove --input k=<dec>`.
        #[cfg(test)]
        #[derive(Clone, Copy, Debug)]
        pub struct #struct_name {
            #( pub #fields: i128, )*
        }

        #[cfg(test)]
        impl ::xark_prover::ProveInputs for #struct_name {
            fn into_inputs(self) -> ::std::vec::Vec<(&'static str, i128)> {
                ::std::vec![ #( (#field_strs, self.#fields), )* ]
            }
        }
    }
    .into()
}

/// `my_square` → `MySquare` (for the `<Name>Inputs` struct). Falls back to
/// `Circuit` for a degenerate all-separator name (e.g. `__`), so the struct is
/// never named just `Inputs`.
fn to_pascal(s: &str) -> String {
    let pascal: String = s
        .split('_')
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect();
    if pascal.is_empty() {
        "Circuit".to_string()
    } else {
        pascal
    }
}
