[package]
name = "xark-secp256k1"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
name = "xark_secp256k1"
path = "src/lib.rs"

[dependencies]
xark = { path = "../xark", default-features = false }
xark-bignum = { path = "../xark-bignum" }
xark-curve = { path = "../xark-curve" }

[dev-dependencies]
k256 = "0.13"
num-bigint = "0.4"
sha2 = "0.10"
xark-ir = { path = "../xark-ir" }
xark-test-harness = { path = "../xark-test-harness" }
